# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoverItemWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


try:
    from PyQt5 import QtCore, QtGui, QtWidgets
except ImportError:
    from PySide2 import QtCore, QtGui, QtWidgets


class Ui_CoverItemWidget(object):
    def setupUi(self, CoverItemWidget):
        CoverItemWidget.setObjectName("CoverItemWidget")
        CoverItemWidget.setMinimumSize(QtCore.QSize(200, 256))
        CoverItemWidget.setMaximumSize(QtCore.QSize(200, 256))
        CoverItemWidget.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(CoverItemWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelCover = CoverLabel(CoverItemWidget)
        self.labelCover.setMinimumSize(QtCore.QSize(180, 180))
        self.labelCover.setText("")
        self.labelCover.setScaledContents(True)
        self.labelCover.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCover.setObjectName("labelCover")
        self.verticalLayout.addWidget(self.labelCover)
        self.labelTitle = QtWidgets.QLabel(CoverItemWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTitle.setFont(font)
        self.labelTitle.setText("")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.labelAuthor = QtWidgets.QLabel(CoverItemWidget)
        self.labelAuthor.setText("")
        self.labelAuthor.setObjectName("labelAuthor")
        self.verticalLayout.addWidget(self.labelAuthor)

        self.retranslateUi(CoverItemWidget)
        QtCore.QMetaObject.connectSlotsByName(CoverItemWidget)

    def retranslateUi(self, CoverItemWidget):
        pass
from .CoverLabel import CoverLabel

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CoverItemWidget = QtWidgets.QWidget()
    ui = Ui_CoverItemWidget()
    ui.setupUi(CoverItemWidget)
    CoverItemWidget.show()
    sys.exit(app.exec_())
