# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoverLabel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


try:
    from PyQt5 import QtCore, QtGui, QtWidgets
except ImportError:
    from PySide2 import QtCore, QtGui, QtWidgets


class Ui_CoverLabel(object):
    def setupUi(self, CoverLabel):
        CoverLabel.setObjectName("CoverLabel")
        CoverLabel.resize(180, 180)
        CoverLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        CoverLabel.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(CoverLabel)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 135, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widgetBottom = QtWidgets.QWidget(CoverLabel)
        self.widgetBottom.setStyleSheet("#widgetBottom {\n"
"    background-color: rgba(0, 0, 0, 150);\n"
"}")
        self.widgetBottom.setObjectName("widgetBottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetBottom)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelHeadset = QtWidgets.QLabel(self.widgetBottom)
        self.labelHeadset.setMinimumSize(QtCore.QSize(16, 16))
        self.labelHeadset.setText("")
        self.labelHeadset.setObjectName("labelHeadset")
        self.horizontalLayout.addWidget(self.labelHeadset)
        self.labelCount = QtWidgets.QLabel(self.widgetBottom)
        self.labelCount.setText("")
        self.labelCount.setObjectName("labelCount")
        self.horizontalLayout.addWidget(self.labelCount)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.labelPlay = QtWidgets.QLabel(self.widgetBottom)
        self.labelPlay.setMinimumSize(QtCore.QSize(16, 16))
        self.labelPlay.setText("")
        self.labelPlay.setObjectName("labelPlay")
        self.horizontalLayout.addWidget(self.labelPlay)
        self.verticalLayout.addWidget(self.widgetBottom)

        self.retranslateUi(CoverLabel)
        QtCore.QMetaObject.connectSlotsByName(CoverLabel)

    def retranslateUi(self, CoverLabel):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CoverLabel = QtWidgets.QWidget()
    ui = Ui_CoverLabel()
    ui.setupUi(CoverLabel)
    CoverLabel.show()
    sys.exit(app.exec_())
