# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pyPro\hoverMenu\Main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 493)
        MainWindow.setStyleSheet(" #MainWindow {  border:none;}")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setStyleSheet("#centralWidget {border:none;}")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setStyleSheet("#widget {border:none;}")
        self.widget.setObjectName("widget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.topWidget = QtWidgets.QWidget(self.widget)
        self.topWidget.setStyleSheet("#widget{   border:none;  }")
        self.topWidget.setObjectName("topWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.W1 = SingeleWidget(self.topWidget)
        self.W1.setObjectName("W1")
        self.gridLayout = QtWidgets.QGridLayout(self.W1)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.filemenu_storeData_3 = B1(self.W1)
        self.filemenu_storeData_3.setText("")
        self.filemenu_storeData_3.setObjectName("filemenu_storeData_3")
        self.gridLayout.addWidget(self.filemenu_storeData_3, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.W1)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.W1)
        self.W2 = SingeleWidget(self.topWidget)
        self.W2.setObjectName("W2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.W2)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtWidgets.QLabel(self.W2)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 1, 1, 1)
        self.filemenu_competitiveProductAnalysis_3 = B2(self.W2)
        self.filemenu_competitiveProductAnalysis_3.setText("")
        self.filemenu_competitiveProductAnalysis_3.setObjectName("filemenu_competitiveProductAnalysis_3")
        self.gridLayout_2.addWidget(self.filemenu_competitiveProductAnalysis_3, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.W2)
        self.W3 = SingeleWidget(self.topWidget)
        self.W3.setObjectName("W3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.W3)
        self.gridLayout_4.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        self.filemenu_throughTrain_4 = B3(self.W3)
        self.filemenu_throughTrain_4.setAutoFillBackground(False)
        self.filemenu_throughTrain_4.setText("")
        self.filemenu_throughTrain_4.setObjectName("filemenu_throughTrain_4")
        self.gridLayout_4.addWidget(self.filemenu_throughTrain_4, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.W3)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.W3)
        self.W4 = SingeleWidget(self.topWidget)
        self.W4.setObjectName("W4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.W4)
        self.gridLayout_5.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 0, 1, 1)
        self.filemenu_throughTrain_3 = B4(self.W4)
        self.filemenu_throughTrain_3.setAutoFillBackground(False)
        self.filemenu_throughTrain_3.setText("")
        self.filemenu_throughTrain_3.setObjectName("filemenu_throughTrain_3")
        self.gridLayout_5.addWidget(self.filemenu_throughTrain_3, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.W4)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.W4)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.topWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_19.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.topWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.horizontalLayout.addLayout(self.verticalLayout_19)
        spacerItem8 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_14.addWidget(self.topWidget)
        self.buttomWidget = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttomWidget.sizePolicy().hasHeightForWidth())
        self.buttomWidget.setSizePolicy(sizePolicy)
        self.buttomWidget.setObjectName("buttomWidget")
        self.Buttom_Vbox = QtWidgets.QVBoxLayout(self.buttomWidget)
        self.Buttom_Vbox.setContentsMargins(0, 0, 0, 0)
        self.Buttom_Vbox.setSpacing(0)
        self.Buttom_Vbox.setObjectName("Buttom_Vbox")
        self.verticalLayout_14.addWidget(self.buttomWidget)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_15.setText(_translate("MainWindow", "店铺数据"))
        self.label_16.setText(_translate("MainWindow", "竞品分析"))
        self.label_19.setText(_translate("MainWindow", "直通工具"))
        self.label_14.setText(_translate("MainWindow", "直通工具"))
        self.label_17.setText(_translate("MainWindow", "个人中心"))
        self.label_18.setText(_translate("MainWindow", "退出登录"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))

from BaseElement import SingeleWidget
from Menu import B1, B2, B3, B4
import tbqrc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

